// Auto-generated by ArduinoGen

// Includes
#include "CmdMessenger.h"
#include "Servo.h"
#include "ElectronicComponentDetector.h"


// Globals
int ledState = HIGH;

// Pin definitions
const char LED = 13;

const char stage1_servo_pin = 5;

const char stage1_limit_switch_pin = 18;


// Constructors
// Attach a new CmdMessenger object to the default Serial port
CmdMessenger cmdMessenger = CmdMessenger(Serial);

// This is the list of recognized commands. These can be commands that can either be sent or received.
// In order to receive, attach a callback function to these events
enum {
	kAcknowledge,
	kError,
	kUnknown,
	kSetLed,
	kPing,
	kPingResult,
	kPong,
	kSetServo,
	kDetachServo,
	kReadSwitch,
	kReadSwitchResult,
	kDecode,
	kDecodeResult
};
const char stage1_servo_index = 0;
char servo_pins[1] = {
	stage1_servo_pin
};
Servo servos[1];

const char stage1_limit_switch_index = 0;
char switches[1] = {
	stage1_limit_switch_pin
};

ElectronicComponentDetector ecd;


void setup() {
	// Init LED pin
	pinMode(LED, OUTPUT);

	servos[stage1_servo_index].attach(stage1_servo_pin);

	pinMode(stage1_limit_switch_pin, INPUT);

ecd.init();
	// Initialize Serial Communication
	Serial.begin(115200);

	// Attach callback methods
	attachCommandCallbacks();


	// Flash led 3 times at the end of setup
	for(int i = 0; i < 3; i++) {
		digitalWrite(LED, HIGH);
		delay(250);
		digitalWrite(LED, LOW);
		delay(250);
	}
	ledState = LOW;
}
void loop() {
	// Process incoming serial data, and perform callbacks
	cmdMessenger.feedinSerialData();
}
// Callbacks define on which received commands we take action
void attachCommandCallbacks() {
	// Attach callback methods
	cmdMessenger.attach(unknownCommand);
	cmdMessenger.attach(kPing, ping);
	cmdMessenger.attach(kSetLed, setLed);
	cmdMessenger.attach(kSetServo, setServo);
	cmdMessenger.attach(kDetachServo, detachServo);
	cmdMessenger.attach(kReadSwitch, readSwitch);
	cmdMessenger.attach(kDecode, Decode);
}

// Called when a received command has no attached function
void unknownCommand() {
	cmdMessenger.sendCmd(kError, kUnknown);
}

// Called upon initialization of Spine to check connection
void ping() {
	cmdMessenger.sendBinCmd(kAcknowledge, kPing);
	cmdMessenger.sendBinCmd(kPingResult, kPong);
}

// Callback function that sets led on or off
void setLed() {
	// Read led state argument, interpret string as boolean
	ledState = cmdMessenger.readBoolArg();
	digitalWrite(LED, ledState);
	cmdMessenger.sendBinCmd(kAcknowledge, kSetLed);
}

void setServo() {
	int indexNum = cmdMessenger.readBinArg<int>();
	if(!cmdMessenger.isArgOk() || indexNum < 0 || indexNum > 1) {
		cmdMessenger.sendBinCmd(kError, kSetServo);
		return;
	}
	int value = cmdMessenger.readBinArg<int>();
	if(!cmdMessenger.isArgOk()){
		cmdMessenger.sendBinCmd(kError, kSetServo);
		return;
	}
	if(!servos[indexNum].attached()){
		servos[indexNum].attach(servo_pins[indexNum]);
	}
	servos[indexNum].write(value);
	cmdMessenger.sendBinCmd(kAcknowledge, kSetServo);
}

void detachServo() {
	int indexNum = cmdMessenger.readBinArg<int>();
	if(!cmdMessenger.isArgOk() || indexNum < 0 || indexNum > 1) {
		cmdMessenger.sendBinCmd(kError, kDetachServo);
		return;
	}
	servos[indexNum].detach();
	cmdMessenger.sendBinCmd(kAcknowledge, kDetachServo);
}

void readSwitch() {
	int indexNum = cmdMessenger.readBinArg<int>();
	if(!cmdMessenger.isArgOk() || indexNum < 0 || indexNum > 1) {
		cmdMessenger.sendBinCmd(kError, kReadSwitch);
		return;
	}
		cmdMessenger.sendBinCmd(kAcknowledge, kReadSwitch);
		cmdMessenger.sendBinCmd(kReadSwitchResult, digitalRead(switches[indexNum]));
}

void Decode() {
	char pad = cmdMessenger.readBinArg<char>();
	char code[5];
	ecd.decode(pad, code, false);
	cmdMessenger.sendBinCmd(kAcknowledge, kDecode);
	cmdMessenger.sendCmdStart(kDecodeResult);
	for(int x = 0 ; x <= 4 ; x++ ) { 
		cmdMessenger.sendCmdBinArg(code[x]);
	}
	cmdMessenger.sendCmdEnd();
}


